<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Zend\\Text\\' => array($vendorDir . '/zendframework/zend-text'),
    'Zend\\Stdlib\\' => array($vendorDir . '/zendframework/zend-stdlib'),
    'Zend\\ServiceManager\\' => array($vendorDir . '/zendframework/zend-servicemanager'),
    'Zend\\Mime\\' => array($vendorDir . '/zendframework/zend-mime'),
    'Zend\\Memory\\' => array($vendorDir . '/zendframework/zend-memory'),
    'Zend\\Mail\\' => array($vendorDir . '/zendframework/zend-mail'),
    'Zend\\Loader\\' => array($vendorDir . '/zendframework/zend-loader'),
    'ZendPdf\\' => array($vendorDir . '/zendframework/zendpdf/library'),
);
